### ISSUE TITLE
Rules in mini_l.yy cannot reference loc variable

### ISSUE THREAD

**Issue by ryan-villena** [EdCarrasco/CS152-CompilerProject#2]
To keep track of location within files, `mini_l.lex` declares a location variable of type `yy::location` [here](https://github.com/EdCarrasco/CS152-CompilerProject/blob/7fb3390462f6bda4b2cb55ed7bef12b8af98ada1/phase3/mini_l.lex#L6). We want to reference this location variable `loc` from our `mini_l.yy` file to be able to print out detailed error messages. For example, we can successfully [throw an error whenever a `main` function is missing](https://github.com/EdCarrasco/CS152-CompilerProject/blob/7fb3390462f6bda4b2cb55ed7bef12b8af98ada1/phase3/mini_l.yy#L126), but we need access to the above `loc` variable in order to be able to print line numbers.

Note that using `#include "mini_l.lex"` does not work, and [declaring `extern yy::location loc`](https://github.com/EdCarrasco/CS152-CompilerProject/blob/7fb3390462f6bda4b2cb55ed7bef12b8af98ada1/phase3/mini_l.yy#L65) does not work either.

**Comment by EdCarrasco** [comment]
According to the TA:

> You can access the "loc" in mini_l.yy file with "@1' if it is "loc" of the first token in the right-hand side of a grammar rule and @2, @3 and so on for other tokens, (Just like $1, $2, and so on). You can just cout << @1 to print out the line number and position.

**Comment by ryan-villena** [comment]
Reopened until we push a working commit
